package orchestrator

const PluginCatalogVersion = "openclaw-2026.7.1-2"

// fixedPluginCatalog is the bundled plugin catalog shipped by OpenClaw 2026.7.1-2.
// Runtime only overlays enabled/disabled state from the local OpenClaw config.
var fixedPluginCatalog = []Plugin{
	{ID: "active-memory", Name: "Active Memory", Description: "Runs a bounded blocking memory sub-agent before eligible conversational replies and injects relevant memory into prompt context.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "admin-http-rpc", Name: "admin-http-rpc", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "alibaba", Name: "alibaba", Enabled: true, Status: "enabled", Source: "fixed_catalog", Configurable: true},
	{ID: "anthropic", Name: "anthropic", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"anthropic"}, Capabilities: []string{"anthropic"}, Configurable: true},
	{ID: "azure-speech", Name: "Azure Speech", Description: "Azure AI Speech text-to-speech (MP3, native Ogg/Opus voice notes, PCM telephony).", Enabled: true, Status: "enabled", Source: "fixed_catalog", Capabilities: []string{"azure", "azure-speech"}, Configurable: true},
	{ID: "bonjour", Name: "Bonjour Gateway Discovery", Description: "Advertise the local OpenClaw gateway over Bonjour/mDNS.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "browser", Name: "browser", Enabled: true, Status: "enabled", Source: "fixed_catalog", Capabilities: []string{"browser"}, Configurable: true},
	{ID: "byteplus", Name: "byteplus", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"byteplus", "byteplus-plan"}, Configurable: true},
	{ID: "canvas", Name: "Canvas", Description: "Experimental Canvas control and A2UI rendering surfaces for paired nodes.", Enabled: true, Status: "enabled", Source: "fixed_catalog", Capabilities: []string{"canvas"}, Configurable: true},
	{ID: "clawrouter", Name: "clawrouter", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"clawrouter"}, Configurable: true},
	{ID: "codex-supervisor", Name: "Codex Supervisor", Description: "Supervise Codex app-server sessions from OpenClaw.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Capabilities: []string{"codex_endpoint_probe", "codex_session_interrupt", "codex_session_read", "codex_session_send", "codex_sessions_list"}, Configurable: true},
	{ID: "cohere", Name: "Cohere", Description: "OpenClaw Cohere provider plugin.", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"cohere"}, Configurable: true},
	{ID: "comfy", Name: "comfy", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"comfy"}, Capabilities: []string{"comfy"}, Configurable: true},
	{ID: "copilot-proxy", Name: "copilot-proxy", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"copilot-proxy"}, Configurable: true},
	{ID: "deepgram", Name: "deepgram", Enabled: true, Status: "enabled", Source: "fixed_catalog", Capabilities: []string{"deepgram"}, Configurable: true},
	{ID: "deepseek", Name: "deepseek", Description: "OpenClaw DeepSeek provider plugin.", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"deepseek"}, Capabilities: []string{"deepseek"}, Configurable: true},
	{ID: "device-pair", Name: "Device Pairing", Description: "Generate setup codes and approve device pairing requests.", Enabled: true, Status: "enabled", Source: "fixed_catalog", Configurable: true},
	{ID: "document-extract", Name: "Document Extraction", Description: "Extract text and fallback page images from local document attachments.", Enabled: true, Status: "enabled", Source: "fixed_catalog", Configurable: true},
	{ID: "duckduckgo", Name: "duckduckgo", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "elevenlabs", Name: "elevenlabs", Enabled: true, Status: "enabled", Source: "fixed_catalog", Capabilities: []string{"elevenlabs"}, Configurable: true},
	{ID: "fal", Name: "fal", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"fal"}, Capabilities: []string{"fal"}, Configurable: true},
	{ID: "file-transfer", Name: "File Transfer", Description: "Fetch, list, and write files on paired nodes via dedicated node commands. Bypasses bash stdout truncation by using base64 over node.invoke for binaries up to 16 MB.", Enabled: true, Status: "enabled", Source: "fixed_catalog", Capabilities: []string{"dir_fetch", "dir_list", "file_fetch", "file_write"}, Configurable: true},
	{ID: "github-copilot", Name: "github-copilot", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"github-copilot"}, Configurable: true},
	{ID: "google", Name: "google", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"google", "google-gemini-cli", "google-vertex"}, Capabilities: []string{"google"}, Configurable: true},
	{ID: "huggingface", Name: "huggingface", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"huggingface"}, Configurable: true},
	{ID: "imessage", Name: "imessage", Enabled: false, Status: "disabled", Source: "fixed_catalog", Channels: []string{"imessage"}, Configurable: true},
	{ID: "litellm", Name: "litellm", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"litellm"}, Capabilities: []string{"litellm"}, Configurable: true},
	{ID: "llm-task", Name: "LLM Task", Description: "Generic JSON-only LLM tool for structured tasks callable from workflows.", Version: "2026.5.21", Enabled: false, Status: "disabled", Source: "fixed_catalog", Capabilities: []string{"llm-task"}, Configurable: true},
	{ID: "lmstudio", Name: "lmstudio", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"lmstudio"}, Configurable: true},
	{ID: "logbook", Name: "Logbook", Description: "Automatic work journal: captures periodic screen snapshots from a paired node and turns them into a reviewable timeline of your day.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "memory-core", Name: "memory-core", Enabled: false, Status: "disabled", Source: "fixed_catalog", Capabilities: []string{"memory_get", "memory_search"}, Configurable: true},
	{ID: "memory-wiki", Name: "Memory Wiki", Description: "Persistent wiki compiler and Obsidian-friendly knowledge vault for OpenClaw.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Capabilities: []string{"wiki_apply", "wiki_get", "wiki_lint", "wiki_search", "wiki_status"}, Configurable: true},
	{ID: "meta", Name: "meta", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"meta"}, Configurable: true},
	{ID: "microsoft", Name: "microsoft", Enabled: true, Status: "enabled", Source: "fixed_catalog", Capabilities: []string{"microsoft"}, Configurable: true},
	{ID: "microsoft-foundry", Name: "microsoft-foundry", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"microsoft-foundry"}, Capabilities: []string{"microsoft-foundry"}, Configurable: true},
	{ID: "migrate-claude", Name: "Claude Migration", Description: "Imports Claude Code and Claude Desktop instructions, MCP servers, skills, and safe configuration into OpenClaw.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "migrate-hermes", Name: "Hermes Migration", Description: "Imports Hermes configuration, memories, skills, and supported credentials into OpenClaw.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "minimax", Name: "minimax", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"minimax", "minimax-portal"}, Capabilities: []string{"minimax", "minimax-portal"}, Configurable: true},
	{ID: "mistral", Name: "mistral", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"mistral"}, Capabilities: []string{"mistral"}, Configurable: true},
	{ID: "novita", Name: "novita", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"novita", "novita-ai", "novitaai"}, Configurable: true},
	{ID: "nvidia", Name: "nvidia", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"nvidia"}, Configurable: true},
	{ID: "oc-path", Name: "OC Path", Description: "Adds the openclaw path CLI for oc:// workspace file addressing.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "ollama", Name: "ollama", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"ollama", "ollama-cloud"}, Capabilities: []string{"node_inference"}, Configurable: true},
	{ID: "open-prose", Name: "OpenProse", Description: "OpenProse VM skill pack with a /prose slash command.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "openai", Name: "openai", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"openai"}, Capabilities: []string{"openai"}, Configurable: true},
	{ID: "opencode", Name: "opencode", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"opencode"}, Capabilities: []string{"opencode"}, Configurable: true},
	{ID: "opencode-go", Name: "opencode-go", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"opencode-go"}, Capabilities: []string{"opencode-go"}, Configurable: true},
	{ID: "openrouter", Name: "openrouter", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"openrouter"}, Capabilities: []string{"openrouter"}, Configurable: true},
	{ID: "phone-control", Name: "Phone Control", Description: "Arm/disarm high-risk phone node commands (camera/screen/writes) with an optional auto-expiry.", Enabled: true, Status: "enabled", Source: "fixed_catalog", Configurable: true},
	{ID: "policy", Name: "Policy", Description: "Adds policy-backed doctor checks for workspace conformance.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "runway", Name: "runway", Enabled: true, Status: "enabled", Source: "fixed_catalog", Configurable: true},
	{ID: "senseaudio", Name: "senseaudio", Enabled: true, Status: "enabled", Source: "fixed_catalog", Capabilities: []string{"senseaudio"}, Configurable: true},
	{ID: "sglang", Name: "sglang", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"sglang"}, Configurable: true},
	{ID: "synthetic", Name: "synthetic", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"synthetic"}, Configurable: true},
	{ID: "talk-voice", Name: "Talk Voice", Description: "Manage Talk voice selection (list/set).", Enabled: true, Status: "enabled", Source: "fixed_catalog", Configurable: true},
	{ID: "telegram", Name: "telegram", Enabled: false, Status: "disabled", Source: "fixed_catalog", Channels: []string{"telegram"}, Configurable: true},
	{ID: "thread-ownership", Name: "Thread Ownership", Description: "Prevents multiple agents from responding in the same Slack thread. Uses HTTP calls to the slack-forwarder ownership API.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "together", Name: "together", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"together"}, Configurable: true},
	{ID: "tts-local-cli", Name: "tts-local-cli", Enabled: true, Status: "enabled", Source: "fixed_catalog", Capabilities: []string{"cli", "tts-local-cli"}, Configurable: true},
	{ID: "vllm", Name: "vllm", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"vllm"}, Configurable: true},
	{ID: "volcengine", Name: "volcengine", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"volcengine", "volcengine-plan"}, Capabilities: []string{"volcengine"}, Configurable: true},
	{ID: "voyage", Name: "voyage", Enabled: true, Status: "enabled", Source: "fixed_catalog", Configurable: true},
	{ID: "vydra", Name: "vydra", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"vydra"}, Capabilities: []string{"vydra"}, Configurable: true},
	{ID: "web-readability", Name: "Web Readability Extraction", Description: "Extract readable article content from local HTML web fetch responses.", Enabled: true, Status: "enabled", Source: "fixed_catalog", Configurable: true},
	{ID: "webhooks", Name: "Webhooks", Description: "Authenticated inbound webhooks that bind external automation to OpenClaw TaskFlows.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Configurable: true},
	{ID: "workboard", Name: "Workboard", Description: "Dashboard workboard for agent-owned issues and sessions.", Enabled: false, Status: "disabled", Source: "fixed_catalog", Capabilities: []string{"workboard_attachment_add", "workboard_attachment_delete", "workboard_attachment_read", "workboard_block", "workboard_board_archive", "workboard_board_create", "workboard_board_delete", "workboard_boards", "workboard_claim", "workboard_comment", "workboard_complete", "workboard_create", "workboard_decompose", "workboard_dispatch", "workboard_heartbeat", "workboard_link", "workboard_list", "workboard_notify_advance", "workboard_notify_events", "workboard_notify_list", "workboard_notify_subscribe", "workboard_notify_unsubscribe", "workboard_promote", "workboard_proof", "workboard_protocol_violation", "workboard_read", "workboard_reassign", "workboard_reclaim", "workboard_release", "workboard_runs", "workboard_specify", "workboard_stats", "workboard_unblock", "workboard_worker_log"}, Configurable: true},
	{ID: "xai", Name: "xai", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"xai"}, Capabilities: []string{"code_execution", "x_search", "xai"}, Configurable: true},
	{ID: "xiaomi", Name: "xiaomi", Enabled: true, Status: "enabled", Source: "fixed_catalog", Providers: []string{"xiaomi", "xiaomi-token-plan"}, Capabilities: []string{"xiaomi"}, Configurable: true},
}

func fixedPlugins() []Plugin {
	return append([]Plugin(nil), fixedPluginCatalog...)
}
